apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    app: {{ include "keycloak.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "keycloak.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "keycloak.name" . }}
    spec:
      containers:
        - name: keycloak
          image: bitnami/keycloak:{{ .Chart.appVersion }}
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_USER
              value: {{ .Values.auth.adminUser }}
            - name: KEYCLOAK_PASSWORD
              value: {{ .Values.auth.adminPassword }}
